--- #YAML:1.0
name:                Rose-DBx-Garden-Catalyst
version:             0.08
abstract:            plant Roses in your Catalyst garden
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst:                      5.7
    Catalyst::View::TT:            0
    CatalystX::CRUD:               0.24
    CatalystX::CRUD::Controller::RHTMLO: 0.1
    CatalystX::CRUD::Model::RDBO:  0.1
    Data::Dump:                    0
    JSON:                          2
    JSON::XS:                      2
    Path::Class:                   0
    Rose::DBx::Garden:             0.11
    Scalar::Util:                  0
    Template:                      0
    Test::More:                    0
    Tree::Simple:                  0
    Tree::Simple::Visitor::ToNestedHash: 0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
