--- #YAML:1.0
name:                Rose-DBx-Garden-Catalyst
version:             0.09_05
abstract:            plant Roses in your Catalyst garden
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst:                      5.7
    CatalystX::CRUD::YUI:          0
    Data::Dump:                    0
    JSON::XS:                      2
    Rose::DB::Object:              0.77
    Rose::DBx::Garden:             0.14
    Rose::DBx::Object::MoreHelpers: 0.01
    Rose::HTMLx::Form::Related:    0.01
    Test::More:                    0
    Tree::Simple:                  0
    Tree::Simple::Visitor::ToNestedHash: 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
