--- #YAML:1.0
name:               Rose-DBx-Garden-Catalyst
version:            0.11
abstract:           plant Roses in your Catalyst garden
author:
    - Peter Karman <karman@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.7
    Catalyst::Plugin::ConfigLoader:  0
    Catalyst::Plugin::Static::Simple:  0
    CatalystX::CRUD::YUI:  0.009
    Data::Dump:           0
    Rose::DB::Object:     0.77
    Rose::DBx::AutoReconnect:  0
    Rose::DBx::Garden:    0.15
    Rose::DBx::Object::MoreHelpers:  0.06
    Rose::HTMLx::Form::Related:  0.12
    Test::More:           0
    Tree::Simple:         0
    Tree::Simple::Visitor::ToNestedHash:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.46
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
