--- #YAML:1.0
name:                Rose-DBx-Garden-Catalyst
version:             0.09
abstract:            plant Roses in your Catalyst garden
license:             ~
author:              
    - Peter Karman <karman@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Catalyst:                      5.7
    Catalyst::Plugin::ConfigLoader: 0
    Catalyst::Plugin::Static::Simple: 0
    CatalystX::CRUD::YUI:          0.004
    Data::Dump:                    0
    Rose::DB::Object:              0.77
    Rose::DBx::Garden:             0.15
    Rose::DBx::Object::MoreHelpers: 0.02
    Rose::HTMLx::Form::Related:    0.07
    Test::More:                    0
    Tree::Simple:                  0
    Tree::Simple::Visitor::ToNestedHash: 0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
