--- #YAML:1.0
name:                Rose-DBx-Garden-Catalyst
version:             0.01
abstract:            plant Roses in your Catalyst garden
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Catalyst:                      5.7
    Catalyst::View::TT:            0
    CatalystX::CRUD:               0.07
    CatalystX::CRUD::Controller::RHTMLO: 0.05
    CatalystX::CRUD::Model::RDBO:  0.05
    Data::Dump:                    0
    JSON::XS:                      0
    Path::Class:                   0
    Rose::DBx::Garden:             0.02
    Template:                      0
    Test::More:                    0
    Tree::Simple:                  0
    Tree::Simple::Visitor::ToNestedHash: 0
    YAML::Syck:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Peter Karman <karman@cpan.org>
